dist: trusty
sudo: required
language: python

services:
  - docker

env:
        BASE_VERSION=v1.3.3
        BUILD_TAG=$BASE_VERSION.$TRAVIS_BUILD_NUMBER
        DOCKER_NAME="$TRAVIS_REPO_SLUG:$BUILD_TAG"
        DOCKER_LATEST="$TRAVIS_REPO_SLUG:latest"

install:
        - echo "Building container"
        - docker build -t $DOCKER_NAME


script:
        - echo "Run tests here"

         
after_success:
        - echo "Tests successful, push to docker hub"
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker push $DOCKER_NAME
        - docker tag $DOCKER_NAME $DOCKER_LATEST
        - docker push $DOCKER_LATEST
