dist: trusty
sudo: required
language: python

services:
  - docker

env:
        BASE_VERSION=v1.3.3
        BUILD_TAG=$BASE_VERSION.$TRAVIS_BUILD_NUMBER

install:
        - echo "Building container"
        - docker build -t $BUILD_TAG $TRAVIS_REPO_SLUG
        


script:
        - echo "Run tests here"

         
after_success:
        - echo "Tests successful, push to docker hub"
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker push $TRAVIS_REPO_SLUG:$BUILD_TAG
        - docker tag $TRAVIS_REPO_SLUG:$BUILD_TAG $TRAVIS_REPO_SLUG:latest
        - docker push $TRAVIS_REPO_SLUG:latest
